import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SGH',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div id='topo'>
          {/* <h1>Header</h1> */}
        </div>
        <div id="principal">
          {children}
        </div>
        <div id='rodape'>
          {/* <h1>Footer</h1> */}
        </div>
      </body>
    </html>
  )
}
