//    ESTILOS.    //
import { Inter } from 'next/font/google';
import './globals.css';
//   /ESTILOS.    //

//    UTIL.    //
import type { Metadata } from 'next';
//    /UTIL.    //
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SGH',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <div className={inter.className}>
          <div id='topo'>
            {/* <h1>Header</h1> */}
          </div>
          <div id="principal">
            {children}
          </div>
          <div id='rodape'>
            {/* <h1>Footer</h1> */}
          </div>
        </div>
      </body>
    </html>
  )
}
